### ISSUE TITLE
Click event doesn't work

### ISSUE THREAD

**Issue by stebaker92** [Ilyaki/StackToNearbyChests#1]
Hi, I really like the idea for this mod but can't seem to get it working

The button is in the correct position but clicking doesn't seem to do anything (i.e. i have 3 diamonds stood next to a chest containing 1 diamond)

I've tried on different zoom levels and still not got it working, i've even tried cloning & debugging, the following line is always false when clicking on the button:
https://github.com/Ilyaki/StackToNearbyChests/blob/master/StackToNearbyChests/ModEntry.cs#L41

(this is using the latest version of SMAPI and stardew valley on steam - windows 10 user)

**Comment by Ilyaki** [comment]
Can you try again with 1.1.1?
It *should* be working now

**Comment by stebaker92** [comment]
Brilliant! Just tested with 1.1.1 and it works! (also like the ability to change the chest radius)
