### ISSUE TITLE
Great! but one ease of life suggestion...

### ISSUE THREAD

**Issue by Alistair1231** [Ilyaki/StackToNearbyChests#3]
Hey.
Great mod! It makes life soooo much easier.
I've got one question though, I play with controller, so  I have to always have to have the mouse right next to me while playing to use your mod...
Would it be possible to either make the button accessible by controller or to make a hotkey for your mod, so I'd be able to map it with xpadder?
CJBCheatsMenu uses 'P' for example. Maybe use it as reference. 
https://github.com/CJBok/SDV-Mods
https://www.nexusmods.com/stardewvalley/mods/4

This change would be GREATLY appreciated. 
Much love, 
Alistair1231

**Comment by Ilyaki** [comment]
I added a binding for controllers.
See the project page: https://www.nexusmods.com/stardewvalley/mods/1787?tab=description

**Comment by Alistair1231** [comment]
Wow cool thx a bunch. 
That's way better than a autohotkey script combined with xpadder ... :D
